# 车辆类型配置
# 宽度要求（米）

vehicles:
  40ft:
    name: "40ft用トレーラー"
    length: 17.0
    width: 2.5
    min_road_width: 3.5  # 最小道路宽度要求
    description: "40フィートコンテナ用トレーラー"
  
  20ft:
    name: "20ft用トレーラー"
    length: 12.5
    width: 2.5
    min_road_width: 3.5
    description: "20フィートコンテナ用トレーラー"
  
  10t:
    name: "10t飛翼車"
    length: 12.0
    width: 2.50
    min_road_width: 3.2
    description: "10トン飛翼車"
  
  4t:
    name: "4t飛翼車"
    length: 9.6
    width: 2.35
    min_road_width: 3.0
    description: "4トン飛翼車"
  
  2t:
    name: "2t箱型トラック"
    length: 6.3
    width: 2.10
    min_road_width: 2.5
    description: "2トン箱型トラック"
